"""Tests for WSL detection and utilities."""

from __future__ import annotations

import os
from unittest.mock import mock_open, patch

from wsl_chrome_mcp.wsl import (
    convert_windows_to_wsl_path,
    convert_wsl_to_windows_path,
    get_windows_chrome_paths,
    get_windows_host_ip,
    is_wsl,
)


class TestIsWsl:
    """Tests for is_wsl() function."""

    def test_detects_wsl_from_wslinterop(self) -> None:
        """Should detect WSL from WSLInterop file."""
        with patch("os.path.exists", return_value=True):
            # Clear cache
            is_wsl.cache_clear()
            assert is_wsl() is True
        is_wsl.cache_clear()

    def test_detects_wsl_from_proc_version(self) -> None:
        """Should detect WSL from /proc/version."""
        wsl_version = "Linux version 5.15.0-microsoft-standard-WSL2"
        with (
            patch("os.path.exists", return_value=False),
            patch("builtins.open", mock_open(read_data=wsl_version)),
        ):
            is_wsl.cache_clear()
            assert is_wsl() is True
        is_wsl.cache_clear()

    def test_detects_wsl_from_env(self) -> None:
        """Should detect WSL from environment variable."""
        with (
            patch("os.path.exists", return_value=False),
            patch("builtins.open", side_effect=FileNotFoundError),
            patch.dict(os.environ, {"WSL_DISTRO_NAME": "Ubuntu"}),
        ):
            is_wsl.cache_clear()
            assert is_wsl() is True
        is_wsl.cache_clear()

    def test_returns_false_when_not_wsl(self) -> None:
        """Should return False when not in WSL."""
        with (
            patch("os.path.exists", return_value=False),
            patch("builtins.open", mock_open(read_data="Linux version 5.15.0-generic")),
            patch.dict(os.environ, {}, clear=True),
        ):
            is_wsl.cache_clear()
            # Need to also patch WSL_DISTRO_NAME to not exist
            env = os.environ.copy()
            env.pop("WSL_DISTRO_NAME", None)
            with patch.dict(os.environ, env, clear=True):
                is_wsl.cache_clear()
                result = is_wsl()
        is_wsl.cache_clear()
        assert result is False


class TestGetWindowsHostIp:
    """Tests for get_windows_host_ip() function."""

    def test_returns_localhost_when_not_wsl(self) -> None:
        """Should return localhost when not in WSL."""
        with patch("wsl_chrome_mcp.wsl.is_wsl", return_value=False):
            get_windows_host_ip.cache_clear()
            assert get_windows_host_ip() == "127.0.0.1"
        get_windows_host_ip.cache_clear()

    def test_parses_resolv_conf(self) -> None:
        """Should parse nameserver from resolv.conf."""
        resolv_content = """# This file was generated by WSL
nameserver 172.25.160.1
"""
        with (
            patch("wsl_chrome_mcp.wsl.is_wsl", return_value=True),
            patch("builtins.open", mock_open(read_data=resolv_content)),
        ):
            get_windows_host_ip.cache_clear()
            assert get_windows_host_ip() == "172.25.160.1"
        get_windows_host_ip.cache_clear()


class TestPathConversion:
    """Tests for path conversion functions."""

    def test_wsl_to_windows_path_manual(self) -> None:
        """Should convert WSL path to Windows path."""
        # Test fallback manual conversion
        with patch("subprocess.run", side_effect=FileNotFoundError):
            result = convert_wsl_to_windows_path("/mnt/c/Users/test/file.txt")
            assert result == "C:\\Users\\test\\file.txt"

    def test_windows_to_wsl_path_manual(self) -> None:
        """Should convert Windows path to WSL path."""
        # Test fallback manual conversion
        with patch("subprocess.run", side_effect=FileNotFoundError):
            result = convert_windows_to_wsl_path("C:\\Users\\test\\file.txt")
            assert result == "/mnt/c/Users/test/file.txt"


class TestGetWindowsChromePaths:
    """Tests for get_windows_chrome_paths() function."""

    def test_returns_expected_paths(self) -> None:
        """Should return list of common Chrome installation paths."""
        paths = get_windows_chrome_paths()
        assert len(paths) > 0
        assert any("chrome.exe" in p.lower() for p in paths)
